### ISSUE TITLE
UTF8/Ascii error decoding bluetooth devices

### ISSUE THREAD

**Issue by chmouel** [trietsch/alfred-bluetooth-connector#6]
```
[....]
2019-12-21 08:25:33.320 system_profiler[36622:989130] SystemInfo-AccessoryFW from dict - Soundcore Spirit Pro = 0x0000
08:25:33 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/user/Dropbox/lfred.alfredpreferences/workflows/user.workflow.D7C82782-9B04-468C-9B97-EF0C088E25D8/workflow/workflow.py", line 2067, in run
    func(self)
  File "list_bluetooth_devices.py", line 70, in main
    wf.send_feedback()
[..]]
```

**Comment by trietsch** [comment]
This repo is not maintained anymore, I've merged this work with another repository: https://github.com/tilmanginzel/alfred-bluetooth-workflow
