### ISSUE TITLE
big sur not working

### ISSUE THREAD

**Issue by Quickshadoww** [trietsch/alfred-bluetooth-connector#7]
hey, its not working in big sur. log from alfred4:

[01:35:25.326] Logging Started...
[01:35:28.233] Bluetooth Device Connector[Script Filter] Queuing argument ''
[01:35:28.469] Bluetooth Device Connector[Script Filter] Script with argv '(null)' finished
[01:35:28.472] ERROR: Bluetooth Device Connector[Script Filter] Code 1: .
01:35:28 workflow.py:2055 DEBUG    ---------- Bluetooth Device Connector (0.1.2) ----------
01:35:28 workflow.py:1462 DEBUG    reading settings from /Users/shm/Library/Application Support/Alfred/Workflow Data/nl.robintrietsch.bluetooth/settings.json
01:35:28 workflow.py:2339 DEBUG    update check not due
01:35:28 workflow.py:1689 DEBUG    loading cached data: /Users/shm/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/nl.robintrietsch.bluetooth/__workflow_update_status.cpickle
01:35:28 workflow.py:2269 DEBUG    update_data: {u'available': False}
2021-01-31 01:35:28.365 system_profiler[11425:624244] SystemInfo-AccessoryFW from dict - shm’s Keyboard = 0x0107
2021-01-31 01:35:28.377 system_profiler[11425:624244] SystemInfo-AccessoryFW from dict - AirPods Pro von shm = 3​A​283
2021-01-31 01:35:28.377 system_profiler[11425:624244] SystemInfo-AccessoryFW - JBL Flip 3: no firmware version info available
01:35:28 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/shm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DF20B7F5-1848-4A40-9895-3A915396514D/workflow/workflow.py", line 2067, in run
    func(self)
  File "list_bluetooth_devices.py", line 70, in main
    wf.send_feedback()
  File "/Users/shm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DF20B7F5-1848-4A40-9895-3A915396514D/workflow/workflow.py", line 2176, in send_feedback
    sys.stdout.write(ET.tostring(root).encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3: ordinal not in range(128)
01:35:28 workflow.py:2097 DEBUG    ---------- finished in 0.102s ----------
[01:35:28.476] Bluetooth Device Connector[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Bluetooth Device Connector'</title><subtitle>'ascii' codec can't decode byte 0xe2 in position 3: ordinal not in range(128)</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[01:35:28.477] WARNING: Bluetooth Device Connector[Script Filter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 64.)'. Row 2, Col 6: 'XML declaration allowed only at the start of the document' in XML:
<?xml version="1.0" encoding="utf-8"?>
<?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Bluetooth Device Connector'</title><subtitle>'ascii' codec can't decode byte 0xe2 in position 3: ordinal not in range(128)</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>

**Comment by trietsch** [comment]
Hi,

Thanks for using this workflow! Did you happen to see the summary of the
repository? This is not maintained anymore, as I've merged my work into:
https://github.com/tilmanginzel/alfred-bluetooth-workflow

That one should work on Big Sur iirc.
