### ISSUE TITLE
BLT not working in Sonoma

### ISSUE THREAD

**Issue by tobiasgerstenberg** [trietsch/alfred-bluetooth-connector#8]
Hi, 

the bluetooth connector stopped working for me since upgrading to Sonoma 14.0 (23A344). I get the following error message. 

![blt_error](https://github.com/trietsch/alfred-bluetooth-connector/assets/1675584/e9b1e939-89b4-4e30-a552-f8ef8fccce7e)

Here is the log. 

```
[10:27:16.238] Logging Started...
[10:27:21.332] Bluetooth Connector[Script Filter] Queuing argument ''
[10:27:21.445] Bluetooth Connector[Script Filter] Script with argv '(null)' finished
[10:27:21.448] ERROR: Bluetooth Connector[Script Filter] Code 1: .
10:27:21 workflow.py:2093 DEBUG    ---------- Bluetooth Connector (0.12.0) ----------
10:27:21 workflow.py:1483 DEBUG    reading settings from /Users/tobiasg/Library/Application Support/Alfred/Workflow Data/de.tilmanginzel.alfred.bluetooth/settings.json
10:27:21 workflow.py:2399 DEBUG    update check not due
10:27:21 workflow.py:1717 DEBUG    loading cached data: /Users/tobiasg/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/de.tilmanginzel.alfred.bluetooth/__workflow_latest_version.pickle
10:27:21 workflow.py:2114 ERROR    Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/tobiasg/Dropbox/work/alfred/Alfred.alfredpreferences/workflows/user.workflow.5E5BC5F6-A469-4356-865B-0091099B99C1/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/tobiasg/Dropbox/work/alfred/Alfred.alfredpreferences/workflows/user.workflow.5E5BC5F6-A469-4356-865B-0091099B99C1/alfred_bluetooth_workflow.py", line 40, in main
    devices = _read_devices()
              ^^^^^^^^^^^^^^^
  File "/Users/tobiasg/Dropbox/work/alfred/Alfred.alfredpreferences/workflows/user.workflow.5E5BC5F6-A469-4356-865B-0091099B99C1/alfred_bluetooth_workflow.py", line 14, in _read_devices
    devices_raw = json.loads(proc.stdout.read())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
10:27:21 workflow.py:2136 DEBUG    ---------- finished in 0.047s ----------
[10:27:21.450] Bluetooth Connector[Script Filter] {
  "items": [
    {
      "title": "Error in workflow 'Bluetooth Connector'",
      "subtitle": "Expecting value: line 1 column 1 (char 0)",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
```

Cheers, 

Tobi

**Comment by trietsch** [comment]
Hey @tobiasgerstenberg! Awesome that the workflow is still working after 5 years without any update 😁

However, I stopped maintaining this, since all the work is merged into https://github.com/tilmanginzel/alfred-bluetooth-workflow

Let me know if that works, and feel free to close this issue then.

**Comment by tobiasgerstenberg** [comment]
Ah, thank you! I think that was actually the one I was using. I'll repost over there (you can close this issue here). Thanks for the quick response! [I just saw that someone posted [the issue](https://github.com/tilmanginzel/alfred-bluetooth-workflow/issues/36) over there already].
